# Install Packages using variables
- name: Install packages using variables
  hosts: db
  become: yes
  vars:
    packages_list:
      - openssh-server
      - apache2
      - git
      - curl
      - ufw
  tasks:
    - name: Install packages from list
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages_list }}"